### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by icem0** [bullitt186/ha-stiebel-control#9]
[logs_heatingpump_compile.txt](https://github.com/user-attachments/files/17686243/logs_heatingpump_compile.txt)

Please could anyone give me a hint.

**Comment by vdiele** [comment]
Please use the values from heatingpump_en_prod.yaml File for heatingpump.yaml File!

**Comment by icem0** [comment]
now it make sense ... Thank You so much ... now it compile ...  i will test it, these days with my WPW 13 / WPM II
